version: "3.9"

services:
  # ────────── SMTP stub (logs e-mails) ──────────
  mail:
    image: bytemark/smtp
    restart: unless-stopped
    networks: [billabear]

  # ────────── Redis (queues + sessions) ──────────
  redis:
    image: redis:5-alpine
    restart: unless-stopped
    networks: [billabear]

  # ────────── Elasticsearch (full-text search) ──────────
  elasticsearch:
    image: elasticsearch:8.17.1
    restart: unless-stopped
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      network.host: 0.0.0.0
    networks: [billabear]

  # ────────── PostgreSQL / Timescale ──────────
  db:
    image: timescale/timescaledb-ha:pg17
    restart: unless-stopped
    environment:
      POSTGRES_DB:       ${PG_DB}
      POSTGRES_USER:     ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [billabear]

  # ────────── PHP-FPM + Billabear code ──────────
  php:
    image: billabear/ubuntu-php-fpm:8.4
    restart: unless-stopped
    depends_on: [db, redis, elasticsearch]
    environment:
      APP_ENV:      ${APP_ENV}
      APP_SECRET:   ${APP_SECRET}
      DATABASE_URL: "pgsql://${PG_USER}:${PG_PASSWORD}@db:5432/${PG_DB}"
      MAILER_DSN:   "log://default"
    volumes:
      - app:/var/www
    networks:
      billabear:
        aliases: [php, app, php-fpm]     # nginx can use any of these

  # ────────── Nginx (served through Traefik) ──────────
  nginx:
    image: getparthenon/ubuntu-nginx:21.04
    restart: unless-stopped
    depends_on: [php]
    volumes:
      - app:/var/www:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro 
    networks: [billabear]
    # ⚠ No "ports:" block — Coolify’s Traefik handles public 80/443.

networks:
  billabear: {}

volumes:
  pgdata: {}
  app: {}
